### ISSUE TITLE
Making My Profile interactive

### ISSUE THREAD

**Issue by vojtechsimetka** [rsksmart/rds-ui#1]
## Task:
- [ ] Modify the `modesl/user` to include all the stuff currently in My Profile and expose it through Web3.Consumer
- [ ] Add Deposit and Withdraw function to Web3Provider which adds crypto to the account (RBTC + RIF)
- [ ] Add this Deposit Withdraw to the UI (probably a dialogs where users can specify amounts)
- [ ] Modify the My Profile so that the number there and the RNS domain look like debit card
- [ ] Display balances in the My Profile page. This should be 2 values for each token - available funds + locked funds

Later on past transactions will be shown in this page as well so please design it sensibly :)

**Comment by fmelo** [comment]
I have two comments, one it's about the second task and the other one about the fifth.
- Withdraw function is ready, but I don't know if we need to change something to use crypto.
- I'm showing the balances in My Profile, but I need to understand what is about available funds, and locked funds.
